version: "3.9"

services:
  perjalanan-app:
    build: .
    container_name: perjalanan_app
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env.docker
    networks:
      - sppd_network

  nginx:
    image: nginx:alpine
    container_name: perjalanan_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - perjalanan-app
    networks:
      - sppd_network

volumes:
  static_volume:

networks:
  sppd_network:
    external: true
